export const defaultFormatters = {
  yearFormat: "%Y",
  quarterFormat: "%b %Y",
  monthFormat: "%b",
  weekFormat: "%d %b",
  dayFormat: "%a %d",
  hourFormat: "%_I %p",
  minuteFormat: "%I:%M %p",
  secondFormat: "%I:%M:%S %p",
  milliSecondFormat: "%L",
};

export const levelDefinition = [
  (d, date, i) => d.startOfYear && date.getFullYear() % 12 === 0 && "yearFormat",
  (d, date, i) => d.startOfYear && date.getFullYear() % 4 === 0 && "yearFormat",
  (d, date, i) => d.startOfYear && date.getFullYear() % 2 === 0 && "yearFormat",
  (d, date, i) => d.startOfYear && "yearFormat",
  (d, date, i) => d.startOfQuarter && "quarterFormat",
  (d, date, i) => d.startOfMonth && "monthFormat",
  (d, date, i) => d.startOfWeek && "weekFormat",
  (d, date, i) => d.startOfDay && i % 2 === 0 && "dayFormat",
  (d, date, i) => d.startOfDay && "dayFormat",
  (d, date, i) => d.startOfHalfDay && "hourFormat",
  (d, date, i) => d.startOfQuarterDay && "hourFormat",
  (d, date, i) => d.startOfEighthOfADay && "hourFormat",
  (d, date, i) => d.startOfHour && date.getHours() % 2 === 0 && "hourFormat",
  (d, date, i) => d.startOfHour && "hourFormat",
  (d, date, i) => d.startOf30Minutes && "minuteFormat",
  (d, date, i) => d.startOf15Minutes && "minuteFormat",
  (d, date, i) => d.startOf5Minutes && "minuteFormat",
  (d, date, i) => d.startOfMinute && "minuteFormat",
  (d, date, i) => d.startOf30Seconds && "secondFormat",
  (d, date, i) => "secondFormat",
]; 